export const PRODUCTS_LIST = 'PRODUCTSLIST'
export const ADD_PRODUCT = 'ADDPRODUCT'
export const REMOVEPRODUCT = 'REMOVEPRODUCT'
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const REJECTION_REQUEST = 'REJECTION_REQUEST'

export const API_URL = 'http://localhost:5000'

export const ADD_OPINION = 'ADDOPINION'
export const OPINION_LIST = 'OPINIONLIST'
export const REGISTER = 'REGISTER'
export const USER_LIST = 'USER_LIST'
export const SEND_EMAIL = 'SEND_EMAIL'